### ISSUE TITLE
Haltestelle wird erst bei Nachfrage verstanden

### ISSUE THREAD

**Issue by mode2k** [philippst/alexa-abfahrtsmonitor#1]
Hallo,
Ich frage: Alexa, frage abfahrtsmonitor ab Lustheide.
Antwort: Es tut mir leid, ich habe die Haltestelle nicht verstanden. [...] Wie heisst die Haltestelle?
Ich: Lustheide
Haltestelle wird gefunden.

Ich spreche beides mal exakt gleich deutlich. Das Verhalten ist beliebig reproduzierbar. Wäre super wenn hier Abhilfe geschaffen werden könnte.

**Comment by philippst** [comment]
Hallo @mode2k,
Danke für Hinweis! Das ist schon komisch, bei der direkten Ansprache hört Alexa "lust heide" also zwei Worte und kann diese keiner Haltestelle zuordnen. Bei der Nachfrage erkennt sie es aber stets korrekt ... Ich habe die Haltestelle Lustheide nun auch in der Schreibform "lust heide" ergänzt, damit sollte es klappen.

**Comment by mode2k** [comment]
Funktioniert wunderbar. Vielen Dank.

**Comment by mode2k** [comment]
Problem tritt leider wieder auf :-(
